
@testset "markdown" begin
  doc = test_pandoc(
    raw"""
Term 1

:   Definition 1

Term 2 with *inline markup*

:   Definition 2
    """;
    toc = false,
    demojify = true,
  )
  @test doc == raw"""
*test.txt*                                                    Test Description

Term 1                                 Definition 1


Term 2 with _inline markup_            Definition 2



Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
"""
end
