@testset "demojify" begin
  doc = test_pandoc("Hello world :wave:"; demojify = true)

  @test doc == """
*test.txt*            For NVIM v0.8.0            Last change: $(CURRENT_DATE)

==============================================================================
Table of Contents                                     *test-table-of-contents*

Hello world

Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
""" broken = true

  doc = test_pandoc("Hello world :wave:"; demojify = false)

  @test doc == """
*test.txt*            For NVIM v0.8.0            Last change: $(CURRENT_DATE)

==============================================================================
Table of Contents                                     *test-table-of-contents*

Hello world :wave:

Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
"""
end
