@testset "markdown" begin
  doc = test_pandoc(
    """
    # panvimdoc

    > Testing block quote

    | testing line
    | block

    ![caption](image.png)

    """;
    toc = false,
  )
  @test doc == """
*test.txt*                                                    Test Description

==============================================================================
1. panvimdoc                                                  *test-panvimdoc*


  Testing block quote

| testing line
| block
==============================================================================
2. Links                                                          *test-links*

1. *caption*: image.png

Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
"""
end
