@testset "para" begin
  doc = test_pandoc(
    raw"""
Pandoc supports definition lists: <https://pandoc.org/MANUAL.html#definition-lists>.
This can be used to generate documentation of mappings.
All of the content in curly braces `{...}` that is part of the header is dropped and a tag is created.
    """;
    toc = false,
    demojify = true,
  )
  @test doc == raw"""
*test.txt*                                                    Test Description

Pandoc supports definition lists:
<https://pandoc.org/MANUAL.htmldefinition-lists>. This can be used to generate
documentation of mappings. All of the content in curly braces `{...}` that is
part of the header is dropped and a tag is created.

Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
"""
end
