-   id: panvimdoc
    name: pandoc to vimdoc
    description: Convert markdown documentation to vimdoc (using docker)
    entry: /panvimdoc.pre-commit.sh
    language: docker
    files: ^README\.md$
    args:
        - '--input-file'
        - README.md
    pass_filenames: false
