# action.yml
name: "panvimdoc"
description: "Convert pandoc input to vimdoc output"
branding:
  icon: file-text
  color: gray-dark
inputs:
  vimdoc:
    description: "Output vimdoc project name"
    required: true
  pandoc:
    description: "Input pandoc file"
    required: true
    default: "README.md"
  version:
    description: "Vim version"
    required: false
    default: "NVIM v0.8.0"
  toc:
    description: "Table of contents"
    required: false
    default: "true"
  description:
    description: "Project description that replaces the first line of the vimdoc"
    required: false
    default: ""
  demojify:
    description: "Strip emojis from the vimdoc"
    required: false
    default: "false"
  dedupsubheadings:
    description: "Add heading to subheading links"
    required: false
    default: "true"
  treesitter:
    description: "Use treesitter for highlighting codeblocks"
    required: false
    default: "true"
  ignorerawblocks:
    description: "Ignore raw blocks when generating vimdoc"
    required: false
    default: "true"
  docmapping:
    description: "Use h4 headers as mapping docs"
    required: false
    default: "false"
  docmappingprojectname:
    description: "Use project name in tag when writing mapping docs"
    required: false
    default: "true"
  shiftheadinglevelby:
    description: "Shift heading levels by specified number"
    required: false
    default: "0"
  incrementheadinglevelby:
    description: "Increment heading levels by specified number"
    required: false
    default: "0"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --project-name
    - ${{ inputs.vimdoc }}
    - --input-file
    - ${{ inputs.pandoc }}
    - --vim-version
    - ${{ inputs.version }}
    - --toc
    - ${{ inputs.toc }}
    - --description
    - ${{ inputs.description }}
    - --dedup-subheadings
    - ${{ inputs.dedupsubheadings }}
    - --demojify
    - ${{ inputs.demojify }}
    - --treesitter
    - ${{ inputs.treesitter }}
    - --ignore-rawblocks
    - ${{ inputs.ignorerawblocks }}
    - --doc-mapping-project-name
    - ${{ inputs.docmappingprojectname }}
    - --doc-mapping
    - ${{ inputs.docmapping }}
    - --shift-heading-level-by
    - ${{ inputs.shiftheadinglevelby }}
    - --increment-heading-level-by
    - ${{ inputs.incrementheadinglevelby }}
