name: panvimdoc

on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
      - name: Build vimdoc
        run: mise tasks run panvimdoc:build
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
