name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
      - name: Run tests
        run: mise tasks run panvimdoc:test
